const nullableNumber = { type: ["number", "null"] };
const nullableString = { type: ["string", "null"] };
const stringArray = { type: "array", items: { type: "string" } };

const sourcedNote = {
  type: "object",
  properties: {
    text: { type: "string" },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    status: { type: "string" },
    sourceSegmentIds: stringArray,
  },
  required: ["text"],
  additionalProperties: true,
};

export const DISTILLATION_JSON_SCHEMA: Record<string, unknown> = {
  type: "object",
  properties: {
    exercises: {
      type: "array",
      items: {
        type: "object",
        properties: {
          evidenceId: { type: "string" },
          name: { type: "string" },
          spokenNames: stringArray,
          movementDescription: nullableString,
          bodyRegions: stringArray,
          category: nullableString,
          startedAtSeconds: nullableNumber,
          endedAtSeconds: nullableNumber,
          status: {
            type: "string",
            enum: [
              "performed",
              "active_instruction",
              "planned_future",
              "mentioned_only",
              "unclear",
            ],
          },
          equipment: stringArray,
          sets: {
            type: "array",
            items: {
              type: "object",
              properties: {
                setNumber: nullableNumber,
                status: {
                  type: "string",
                  enum: ["completed", "planned", "unclear"],
                },
                reps: nullableNumber,
                weightValue: nullableNumber,
                weightUnit: nullableString,
                durationSeconds: nullableNumber,
                restAfterSeconds: nullableNumber,
                rpe: nullableNumber,
                evidence: stringArray,
              },
              required: ["status", "evidence"],
            },
          },
          cues: stringArray,
          userObservations: stringArray,
          painObservations: stringArray,
          progressionSuggestions: stringArray,
          confidence: { type: "number", minimum: 0, maximum: 1 },
        },
        required: [
          "evidenceId",
          "name",
          "spokenNames",
          "bodyRegions",
          "status",
          "equipment",
          "sets",
          "cues",
          "userObservations",
          "painObservations",
          "progressionSuggestions",
          "confidence",
        ],
      },
    },
    sessionSignals: {
      type: "array",
      items: {
        type: "object",
        properties: {
          type: {
            type: "string",
            enum: [
              "accomplishment",
              "improvement",
              "pain",
              "next_session",
              "difficulty",
              "energy",
              "general",
            ],
          },
          text: { type: "string" },
          timestampSeconds: nullableNumber,
        },
        required: ["type", "text"],
      },
    },
  },
  required: ["exercises", "sessionSignals"],
};

export const EXTRACTION_JSON_SCHEMA: Record<string, unknown> = {
  type: "object",
  properties: {
    sessionId: { type: "string" },
    extractionVersion: { type: "string" },
    exercises: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          canonicalName: { type: "string" },
          spokenNames: stringArray,
          category: nullableString,
          bodyRegions: stringArray,
          equipment: stringArray,
          sequenceNumber: { type: "number" },
          startedAtSeconds: nullableNumber,
          endedAtSeconds: nullableNumber,
          planned: { type: "boolean" },
          completed: { type: "boolean" },
          sets: {
            type: "array",
            items: {
              type: "object",
              properties: {
                setNumber: { type: "number" },
                setType: nullableString,
                plannedReps: nullableNumber,
                completedReps: nullableNumber,
                weight: { type: ["object", "null"], additionalProperties: true },
                duration: { type: ["object", "null"], additionalProperties: true },
                restAfterSeconds: nullableNumber,
                rpe: nullableNumber,
                completed: { type: "boolean" },
                formQuality: nullableString,
                userNotes: { type: "array", items: sourcedNote },
                trainerNotes: { type: "array", items: sourcedNote },
                confidence: { type: "number", minimum: 0, maximum: 1 },
                sourceSegmentIds: stringArray,
              },
              required: [
                "setNumber",
                "completed",
                "userNotes",
                "trainerNotes",
                "confidence",
                "sourceSegmentIds",
              ],
            },
          },
          techniqueNotes: { type: "array", items: sourcedNote },
          userNotes: { type: "array", items: sourcedNote },
          trainerNotes: { type: "array", items: sourcedNote },
          painObservations: { type: "array", items: { type: "object", additionalProperties: true } },
          progressionSuggestion: { anyOf: [sourcedNote, { type: "null" }] },
          confidence: { type: "number", minimum: 0, maximum: 1 },
        },
        required: [
          "id",
          "canonicalName",
          "spokenNames",
          "bodyRegions",
          "equipment",
          "sequenceNumber",
          "planned",
          "completed",
          "sets",
          "techniqueNotes",
          "userNotes",
          "trainerNotes",
          "painObservations",
          "confidence",
        ],
      },
    },
    sessionNotes: stringArray,
    techniqueThemes: stringArray,
    accomplishments: stringArray,
    improvementAreas: stringArray,
    painObservations: { type: "array", items: { type: "object", additionalProperties: true } },
    nextSessionPlan: { type: ["object", "null"], additionalProperties: true },
    overallDifficulty: { type: ["object", "null"], additionalProperties: true },
    energyLevel: { type: ["object", "null"], additionalProperties: true },
    openQuestions: stringArray,
  },
  required: [
    "sessionId",
    "extractionVersion",
    "exercises",
    "sessionNotes",
    "techniqueThemes",
    "accomplishments",
    "improvementAreas",
    "painObservations",
    "openQuestions",
  ],
};
